### PR TITLE
Create dutch localisation

### PR DESCRIPTION
**Pull request by barryvdh**
Based on https://www.zingchart.com/blog/2014/05/19/localize-online-charts/

Not sure if the date format is correct, I based it on http://php.net/manual/en/function.date.php

I wanted to translate 'About Zingchart' to 'Over Zingchart', but couldn't find the translation key..

Perhaps it's good to include a template also on Github, to make it easier for people to contribute. By adding it to the package, everyone doesn't have to create their own version.

### CODE REVIEW

**Comment by barryvdh** [comment]
Another option would be to automatically load the language files, similar to the loading of modules, when available and when the object is not already set (in case of overwriting)

**Comment by mike-schultz** [comment]
Hi @barryvdh, thank you for reaching out to us. We have decided to go with your idea of letting people contribute to a repository of locales. The repository is located here: https://github.com/zingchart/zingchart-locale. Feel free to submit a pull request to that repository so we can credit you properly.

The `About ZingChart` is purposely left out since that is related to our licensing scheme (which can be removed when the proper license is included). I have put an issue into our internal ticketing system to review this.

**Comment by barryvdh** [comment]
OK good :)
Will you also add that to bower/npm?

**Comment by mike-schultz** [comment]
@barryvdh Done! https://github.com/zingchart/zingchart-locale

**Pull request closed without merging**
